from dotenv import load_dotenv
load_dotenv()

import os

TRACKMANIA_CLIENT_ID=os.environ['TRACKMANIA_CLIENT_ID']
TRACKMANIA_CLIENT_SECRET=os.environ['TRACKMANIA_CLIENT_SECRET']

TRACKMANIA_APP_ID=os.environ['TRACKMANIA_APP_ID']
TRACKMANIA_LOGIN=os.environ['TRACKMANIA_LOGIN']
TRACKMANIA_PASSWORD=os.environ['TRACKMANIA_PASSWORD']
